### ISSUE TITLE
No such file or directory: '/tmp/pip-install-f0D9Yv/grit/README.rst

### ISSUE THREAD

**Issue by vsile** [rsgalloway/grit#1]
I can't install grit from pip
```
user@c107 ~ $ pip install grit
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Collecting grit
  Downloading https://files.pythonhosted.org/packages/2d/76/cfb08bcd87830694d9c5eb066d393fe3c924f8f8e527d26c866d9c4143eb/grit-0.1.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 539kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-FKPTon/grit/setup.py", line 23, in <module>
        long_description=open(os.path.join(os.path.dirname(__file__), 'README.rst')).read(),
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-FKPTon/grit/README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-FKPTon/grit/
```
Python 2.7.12
Linux Mint 18.3

How to fix it?

**Comment by vsile** [comment]
Maybe, this is because MANIFEST.in file is [missing](https://github.com/ozgur/python-linkedin/issues/19#issuecomment-21231252)?

**Comment by rsgalloway** [comment]
Thanks for the report. I've pushed a fix for this, but you'll have to run the install from the repo:

$ sudo python setup.py install

Looks like pypi has changed a lot since I last used it and I'll have to refigure out all the hoops they want me to jump through to get this uploaded.
